### ISSUE TITLE
Cannot open AperiCloud_Arbitrary__mini_polyg3d.xml

### ISSUE THREAD

**Issue by Micmac-test** [luc-girod/MicMacWorkflowsByLucGirod#1]
I'm using micmac git revision : v1.0.beta13-256-g6cc2b94c7
Changing in the script Statue.sh several lines:

74 mm3d Tapioca MulScale .*$EXTENSION 500 2000 
     mm3d Tapioca MulScale .*$EXTENSION 500 2400 @SFS

86 mm3d AperiCloud .*$EXTENSION Ori-Arbitrary SH=$SH
     mm3d AperiCloud .*$EXTENSION Arbitrary SH=$SH

95 mm3d C3DC Statue .*$EXTENSION Ori-Arbitrary ZoomF=$ZOOM Masq3D=AperiCloud_Arbitrary__mini.ply
   mm3d C3DC Statue .*$EXTENSION Arbitrary ZoomF=$ZOOM Masq3D=AperiCloud_Arbitrary__mini.ply

I'm getting an error:

make: 'all' is up to date.
For required file [./AperiCloud_Arbitrary__mini_polyg3d.xml]
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    Cannot open
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 417
|          of file : /home/b/src64/micmac/src/util/stringifie.cpp
-------------------------------------------------------------
Bye  (press enter)

For required file [./Ori-Arbitrary/FileImSel.xml]
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    Cannot open

FAIL IN : 
/home/b/src64/micmac/bin/mm3d MMByP   Statue ".*jpg" Arbitrary  Masq3D=AperiCloud_Arbitrary__mini.ply  UseGpu=0 ExpImSec=1 SH= Purge=1 Do=APMCR ZoomF=2

[mm3d-LogFile.txt](https://github.com/luc-girod/MicMacWorkflowsByLucGirod/files/2342493/mm3d-LogFile.txt)

[WarnApero.txt](https://github.com/luc-girod/MicMacWorkflowsByLucGirod/files/2342494/WarnApero.txt)

**Comment by luc-girod** [comment]
Hei,

It looks like you did not make a 3D mask on your AperiCloud using:
mm3d SaisieMasqQT AperiCloud_Arbitrary.ply
