### ISSUE TITLE
Typo in DroneNadir

### ISSUE THREAD

**Issue by ademsaglam** [luc-girod/MicMacWorkflowsByLucGirod#3]
Hello Luc,

First of all, many thanks to share your files with everyone. It helps really a lot!
I saw the following type at line 29 in DroneNadir.sh:

while getopts "e:x:y:u:speao:r:z:h" opt; do

where "speao" should be "spcao", right? I don't know if this changes anything, I have not tested the program yet.

Best,
Adem

**Comment by luc-girod** [comment]
Hei Adem,
I didn't see your comment until now, and you are in fact right, it was a typo!

Corrected in commit a49b74cd699257a6f953897d7b7590c68203fc45
