### ISSUE TITLE
Problème d'assemblage d'orthomosaïque

### ISSUE THREAD

**Issue by jfvilleforceix** [luc-girod/MicMacWorkflowsByLucGirod#5]
Bonjour Luc,

J'essaie d'utiliser Tawny pour générer une orthoimage sur un gros jeu de données et j'obtiens à la fin des dalles d'ortho non assemblées comme le cas que tu traites dans ton script SatPleiades-1.sh à la ligne 234.

Tu proposes d'utiliser otbcli_TileFusion et je souhaiterais savoir comment tu l'utiliserais sur 4 dalles avec le fichier de géoréférencement qui est Orthophotomosaic.tfw ?

Merci d'avance.

**Comment by luc-girod** [comment]
Oops, never saw that issue. Before I close it, I'd like to answer it with my current solution.

For cleanup at the end of my scripts, I run some gdal commands, as well as, if necessary :
`mosaic_micmac_tiles --filename Orthophotomosaic`
From the python library https://github.com/iamdonovan/spymicmac
